spring.application.name=SklepCool
spring.datasource.url=jdbc:postgresql://ep-small-bird-anp7117q-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_iV8lOqhrn0WQ&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update

## minutes
cart.expiration-minutes=${EXPIRATION_MINUTES:20}
cart.cleanup-cron=${CLEANUP_CRON:0 */20 * * * *}